# Generated by Django 5.1.1 on 2024-10-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.DateField(auto_now_add=True, verbose_name='date of check_out of book')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='date of  check_in of book')),
                ('number_of_days_late', models.PositiveIntegerField(default=0, verbose_name='Tracks number of days book is late for return')),
                ('late', models.BooleanField(default=False, verbose_name='Whether book is late for return or not')),
                ('returned', models.BooleanField(default=False, verbose_name='Whether the book has been returned')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='date when the book is due')),
                ('penalty_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='number of days late')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_transactions', to='Library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
